// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJFJ4v_KRYFbtGQlFhbXcCHjKWwiDABE',
    appId: '1:662464051834:web:1a89006572c7fb625c19c3',
    messagingSenderId: '662464051834',
    projectId: 'iter-a9cb4',
    authDomain: 'iter-a9cb4.firebaseapp.com',
    storageBucket: 'iter-a9cb4.appspot.com',
    measurementId: 'G-KXK9P4611E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDljQy5r9X0KaSpp1xCGjw-uWTTG-W_ik',
    appId: '1:662464051834:android:31722befdbe487265c19c3',
    messagingSenderId: '662464051834',
    projectId: 'iter-a9cb4',
    storageBucket: 'iter-a9cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3q9SOGH_yK2IzHK71XQYnKB0H3GO7YQ',
    appId: '1:662464051834:ios:9813fb383e4f39d35c19c3',
    messagingSenderId: '662464051834',
    projectId: 'iter-a9cb4',
    storageBucket: 'iter-a9cb4.appspot.com',
    iosClientId: '662464051834-njtllaajlrbigthpsabk99o71v13gtl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.iter',
  );
}
